artifacts_root: artifacts


data_ingestion_manipulation:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/abalone.csv
  source_URL: https://raw.githubusercontent.com/AgoCem/Abalone_Age_Prediction/main/abalone.csv
  save_training_file: artifacts/training
 
model_preparation_training:
  root_dir: artifacts/training
  local_data_file: artifacts/training/train.csv
  trained_model_path: artifacts/training